name: Generate rx.js.cool

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Generate
        run: |-
          sudo timedatectl set-timezone Asia/Shanghai
          yarn install
          yarn generate
      - name: Commit and push
        run: |-
          git config --global user.email "i@js.cool" && git config --global user.name "Github Bot"
          cd dist
          git init -b main
          git add . && git commit -m ":memo: Auto Generate" || exit 0
          git push --force "https://${GH_TOKEN}@github.com/willin/rx.js.cool.git" main:gh-pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
